name: "Build container image"

env:
  NAME: "conteneur"
  # Si votre identifiant de compte GitHub comporte des majuscules, remplacez
  # '${{ github.repository_owner }}' par votre identifiant en miniscule uniquement
  REGISTRY: ghcr.io/${{ github.repository_owner }}

# Ce workflow ne sera exécuté que lors d'un 'push' sur la branche 'main'
on:
  push:
    branches:
      - main

# Authorise :
# - Accès en lecture seule au contenu du dépôt Git
# - Accès en lecture/écriture au "packages" pour avoir l'accès au registre de
#   conteneurs de GitHub
permissions:
  contents: read
  packages: write

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      # Récupération du dépôt Git
      - name: Checkout repo
        uses: actions/checkout@v4

      # Construction de l'image de conteneur avec buildah
      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.NAME }}
          image: ${{ env.NAME }}
          tags: latest
          containerfiles: ${{ env.NAME }}/Containerfile
          layers: false
          oci: true

      # Publication de l'image de conteneur dans le regsitre de GitHub avec podman
      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.NAME }}
          tags: latest
